lst=[10,20,30,5,20]
print("List elements::",lst)
lst.append(1)
print("Append 1 to list::",lst)
lst.sort()
print("Sorted list::",lst)
lst.reverse()
print("Reverse List::",lst)
lst.pop(3)
print("Pop 3rd element from list",lst)
print("Count of 20 in list::",lst.count(20))
lst.clear()
print("List.clear()::",lst)
